import type { AppState } from "./types";
import { DEFAULT_GULF_FEES, DEFAULT_PRICING } from "./cod";

const today = "2026-08-28";

export const SEED: AppState = {
  settings: {
    usdToDzd: 245,
    algeriaConfirm: 0.48,
    algeriaDelivered: 0.42,
    algeriaDeliveryDzd: 500,
    algeriaReturnDzd: 350,
    algeriaCallCenterDzd: 180,
    gulfFees: { ...DEFAULT_GULF_FEES },
    algeriaFeesUsd: {
      leadFee: 0.3,
      confirmFee: 0.6,
      extraPerConfirm: 0,
      deliveredFee: 1.2,
      codPercent: 0.04,
    },
    pricing: { ...DEFAULT_PRICING },
  },
  plProducts: [
    {
      id: "g-a",
      region: "gulf",
      name: "A · دونجل بث",
      productCost: 4,
      leads: 1500,
      orders: 1000,
      delivered: 500,
      unitSellPrice: 50,
      totalSales: 25000,
      adsSpend: 7500,
      testSpend: 200,
      adAccount: 200,
      bonus: 0,
      currency: "USD",
    },
    {
      id: "g-b",
      region: "gulf",
      name: "B · حزام حراري",
      productCost: 5,
      leads: 1500,
      orders: 1000,
      delivered: 500,
      unitSellPrice: 50,
      totalSales: 25000,
      adsSpend: 13000,
      testSpend: 500,
      adAccount: 300,
      bonus: 0,
      currency: "USD",
    },
    {
      id: "g-c",
      region: "gulf",
      name: "C · قهوة ماكا",
      productCost: 5,
      leads: 1500,
      orders: 1000,
      delivered: 500,
      unitSellPrice: 50,
      totalSales: 25000,
      adsSpend: 13000,
      testSpend: 500,
      adAccount: 300,
      bonus: 0,
      currency: "USD",
    },
    {
      id: "dz-a",
      region: "algeria",
      name: "A · دونجل بث",
      productCost: 4.2,
      leads: 800,
      orders: 380,
      delivered: 160,
      unitSellPrice: 61.25,
      totalSales: 9800,
      adsSpend: 2100,
      testSpend: 120,
      adAccount: 80,
      bonus: 0,
      currency: "USD",
    },
    {
      id: "dz-b",
      region: "algeria",
      name: "B · سيروم نحاسي",
      productCost: 3.1,
      leads: 600,
      orders: 270,
      delivered: 110,
      unitSellPrice: 56.36,
      totalSales: 6200,
      adsSpend: 1400,
      testSpend: 90,
      adAccount: 40,
      bonus: 0,
      currency: "USD",
    },
  ],
  operations: [
    {
      region: "gulf",
      salaries: 2000,
      vatDuty: 500,
      rent: 500,
      utilities: 300,
      management: 4000,
      extra: 0,
      currency: "USD",
    },
    {
      region: "algeria",
      salaries: 450,
      vatDuty: 80,
      rent: 120,
      utilities: 40,
      management: 200,
      extra: 35,
      currency: "USD",
    },
  ],
  stability: {
    gulf: {
      quantity: 100,
      testCost: 4,
      costPct: 0.3,
      confirmationRate: 0.6,
      deliveredRate: 0.54,
      sellingPriceLocal: 199,
      altPriceLocal: 179,
      productCost: 5,
      fxToUsd: 3.7,
    },
    algeria: {
      quantity: 100,
      testCost: 3.2,
      costPct: 0.25,
      confirmationRate: 0.48,
      deliveredRate: 0.42,
      sellingPriceLocal: 6900,
      altPriceLocal: 5900,
      productCost: 4.2,
      fxToUsd: 245,
    },
  },
  stock: [
    {
      id: "st-1",
      region: "gulf",
      country: "KSA",
      name: "دونجل بث G2",
      sku: "G2-KSA",
      qty: 500,
      dailySales: 30,
      leadTimeDays: 22,
      bufferDays: 5,
      unitCostUsd: 4.8,
      sellingPrice: 199,
      currency: "SAR",
      warehouse: "الرياض",
      updatedAt: today,
    },
    {
      id: "st-2",
      region: "gulf",
      country: "QA",
      name: "قهوة ماكا",
      sku: "MACA-QA",
      qty: 180,
      dailySales: 8,
      leadTimeDays: 18,
      bufferDays: 5,
      unitCostUsd: 6.2,
      sellingPrice: 249,
      currency: "QAR",
      warehouse: "الدوحة",
      updatedAt: today,
    },
    {
      id: "st-3",
      region: "algeria",
      country: "DZ",
      name: "دونجل بث G2",
      sku: "G2-DZ",
      qty: 220,
      dailySales: 12,
      leadTimeDays: 28,
      bufferDays: 7,
      unitCostUsd: 5.1,
      sellingPrice: 6900,
      currency: "DZD",
      warehouse: "الجزائر العاصمة",
      updatedAt: today,
    },
    {
      id: "st-4",
      region: "algeria",
      country: "DZ",
      name: "حزام حراري",
      sku: "BELT-DZ",
      qty: 90,
      dailySales: 4,
      leadTimeDays: 25,
      bufferDays: 6,
      unitCostUsd: 7.4,
      sellingPrice: 4900,
      currency: "DZD",
      warehouse: "وهران",
      updatedAt: today,
    },
  ],
  cash: [
    { id: "c1", region: "gulf", date: "2026-08-03", type: "out", category: "ads", label: "إعلانات ميتا KSA", amount: 4200, currency: "USD" },
    { id: "c2", region: "gulf", date: "2026-08-08", type: "out", category: "product", label: "شحنة علي بابا", amount: 3100, currency: "USD" },
    { id: "c3", region: "gulf", date: "2026-08-18", type: "in", category: "cod", label: "تحصيل COD أسبوعي", amount: 9800, currency: "USD" },
    { id: "c4", region: "gulf", date: "2026-08-25", type: "out", category: "ops", label: "رواتب وإيجار", amount: 2300, currency: "USD" },
    { id: "c5", region: "algeria", date: "2026-08-05", type: "out", category: "ads", label: "إعلانات فيسبوك DZ", amount: 900, currency: "USD" },
    { id: "c6", region: "algeria", date: "2026-08-12", type: "in", category: "cod", label: "تحصيل ياليدين", amount: 1860000, currency: "DZD" },
    { id: "c7", region: "algeria", date: "2026-08-20", type: "out", category: "ops", label: "رواتب + كراء", amount: 210000, currency: "DZD" },
    { id: "c8", region: "algeria", date: "2026-08-22", type: "out", category: "shipping", label: "توصيل ومرتجع", amount: 145000, currency: "DZD" },
  ],
  shipments: [
    {
      id: "ab-1",
      productName: "G2 Miracast Dongle",
      supplier: "Shenzhen Cast Tech",
      alibabaUrl: "https://www.alibaba.com",
      chinaPrice: 3.4,
      weightKg: 0.12,
      seaRatePerKg: 9,
      qty: 1000,
      customsPct: 0.08,
      otherFees: 180,
      region: "gulf",
      destination: "KSA",
      status: "shipped",
      orderDate: "2026-08-10",
      productionDays: 8,
      transitDays: 18,
      note: "شحنة بحر للرياض",
    },
    {
      id: "ab-2",
      productName: "Tongkat Ali Maca Coffee",
      supplier: "Guangzhou Herb",
      alibabaUrl: "https://www.alibaba.com",
      chinaPrice: 4.1,
      weightKg: 0.35,
      seaRatePerKg: 9,
      qty: 500,
      customsPct: 0.12,
      otherFees: 90,
      region: "gulf",
      destination: "QA",
      status: "production",
      orderDate: "2026-08-20",
      productionDays: 10,
      transitDays: 16,
      note: "",
    },
    {
      id: "ab-3",
      productName: "G2 Dongle Algeria lot",
      supplier: "Shenzhen Cast Tech",
      alibabaUrl: "https://www.alibaba.com",
      chinaPrice: 3.4,
      weightKg: 0.12,
      seaRatePerKg: 11,
      qty: 600,
      customsPct: 0.3,
      otherFees: 220,
      region: "algeria",
      destination: "DZ",
      status: "ordered",
      orderDate: "2026-08-25",
      productionDays: 10,
      transitDays: 22,
      note: "جمارك الجزائر 30%",
    },
  ],
  winners: [
    {
      id: "w1",
      name: "دونجل بث لاسلكي G2",
      niche: "منزل / تلفزيون",
      region: "gulf",
      status: "winner",
      chinaPrice: 3.4,
      sellingPrice: 53,
      weightKg: 0.12,
      wow: 8,
      problem: 9,
      competition: 6,
      perceivedValue: 8,
      scalability: 9,
      availability: 7,
      alibabaUrl: "",
      notes: "رابحة في السعودية وقطر",
      testedAt: "2026-07-12",
    },
    {
      id: "w2",
      name: "قهوة تونغكات علي ماكا",
      niche: "صحة رجال",
      region: "gulf",
      status: "testing",
      chinaPrice: 4.1,
      sellingPrice: 66,
      weightKg: 0.35,
      wow: 7,
      problem: 8,
      competition: 5,
      perceivedValue: 9,
      scalability: 7,
      availability: 6,
      alibabaUrl: "",
      notes: "اختبار سعر 249 ر.س",
    },
    {
      id: "w3",
      name: "حزام حراري لاسلكي",
      niche: "آلام ظهر",
      region: "algeria",
      status: "testing",
      chinaPrice: 5.8,
      sellingPrice: 20,
      weightKg: 0.45,
      wow: 6,
      problem: 8,
      competition: 7,
      perceivedValue: 7,
      scalability: 6,
      availability: 5,
      alibabaUrl: "",
      notes: "اختبار الجزائر — تأكيد ضعيف حتى الآن",
    },
    {
      id: "w4",
      name: "سيروم ببتيد نحاسي",
      niche: "عناية بشرة",
      region: "algeria",
      status: "not_tested",
      chinaPrice: 2.4,
      sellingPrice: 18,
      weightKg: 0.08,
      wow: 7,
      problem: 7,
      competition: 4,
      perceivedValue: 8,
      scalability: 8,
      availability: 6,
      alibabaUrl: "",
      notes: "مرشح للاختبار",
    },
  ],
};
